baseURL = "https://polygeist.mit.edu/"
languageCode = "en-us"
title = "Polygeist"
theme = "mlir"

hasCJKLanguage = true
metaDataFormat = "yaml"

pygmentsCodeFences = true
pygmentsUseClasses = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

disablePathToLower = true

[Params]

    # Souce Code repository section
    description = "Polygeist MLIR Polyhedral Compiler for C/C++"
    github_repository = "https://github.com/wsmoses/Polygeist"
    version = ""

    # Analytic section
    google_analytics_id = "G-SBS5VNKHC1" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Theme settings section
    # Theme color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "slide-menu" # "open-menu" or "slide-menu"

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts"
    ]

# Global menu section
[[menu.main]]
    name = "Community"
    weight = 3

[[menu.main]]
    name = "Source"
    weight = 10
    url = "https://github.com/wsmoses/Polygeist"

[[menu.main]]
    name = "Bugs"
    weight = 20
    url = "https://github.com/wsmoses/Polygeist/issues"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
